# Generated by Django 6.0.7 on 2026-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'quantity_in_stock'], name='catalog_pro_is_acti_957ca8_idx'),
        ),
    ]
