# Generated by Django 6.0.7 on 2026-07-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
