from django.db import migrations


def create_sales_team_group(apps, schema_editor):
    """A data migration: seeds a 'Sales Team' group with the standard
    add/change/delete permissions on Product, auto-generated by Django for
    every model. Sales reps and managers get added to this group (manually,
    via the admin, or by an account being created with that role) instead
    of each user getting permissions assigned one by one.

    We use get_or_create() for the ContentType/Permissions rather than
    just querying for them: Django normally creates them via a
    post_migrate signal, but that signal doesn't fire until the very end
    of the whole `migrate` run — too late for a data migration that needs
    them right now, in the middle of that same run.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    product_ct, _ = ContentType.objects.get_or_create(
        app_label="catalog", model="product",
    )

    permissions = []
    for action, name in [
        ("add", "Can add product"),
        ("change", "Can change product"),
        ("delete", "Can delete product"),
    ]:
        permission, _ = Permission.objects.get_or_create(
            content_type=product_ct,
            codename=f"{action}_product",
            defaults={"name": name},
        )
        permissions.append(permission)

    group, _created = Group.objects.get_or_create(name="Sales Team")
    group.permissions.set(permissions)


def remove_sales_team_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Sales Team").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sales_team_group, remove_sales_team_group),
    ]
