"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads BASE_DIR/.env into os.environ, if that file exists — see Module 15.
# .env itself is gitignored (never commit real secrets); .env.example
# documents every variable this file reads, with safe placeholder values.
# A real deployment (Module 16) sets these as actual environment
# variables instead — load_dotenv() is a no-op if no .env file is found,
# so this doesn't interfere with that.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The hardcoded fallback keeps `runserver` working out of the box for
# anyone who clones this repo without writing a .env file first — but
# `manage.py check --deploy` (see the Module 15 lesson) specifically
# flags this exact "django-insecure-" prefix as a real, live security
# check (security.W009), precisely so nobody ships this fallback by accident.
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-_zq*!7m)0il*(txh(5en%c!#emx2y6q8r9f+jrjufk&8!6)#9v"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True so local dev needs zero setup — Module 16's Docker
# Compose config explicitly sets DEBUG=False in its environment instead
# of relying on this default, which is exactly the kind of thing
# check --deploy (security.W018) exists to catch if anyone forgets.
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Comma-separated in the env var (there's no list type in an env var),
# e.g. ALLOWED_HOSTS=atlas.example,www.atlas.example
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]

if not DEBUG:
    # These all assume the site is served over HTTPS — true of any real
    # deployment, never true of plain local `runserver`, hence gating on
    # DEBUG rather than setting them unconditionally.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 1 year, the value Django's own docs use once you're confident HTTPS
    # works site-wide — start much lower (e.g. 3600) the first time you
    # enable HSTS on a real domain, since a mistake here is only fixable
    # by waiting out the cache time in every visitor's browser.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    # Local apps
    'accounts',
    'pages',
    'catalog',
    'customers',
    'orders',
    'notifications',
]
# Note: no 'api' entry here — api/ is just a URLconf package (a router +
# urls.py), with no models/templates/admin of its own, so it doesn't need
# to be a registered Django app. Every model it exposes already belongs to
# an app that IS registered (catalog, customers, orders).

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-wide templates (e.g. base.html) live in BASE_DIR/templates.
        # APP_DIRS below additionally auto-discovers templates inside each
        # app's own templates/<app_name>/ folder.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Makes {{ unread_notification_count }} available in every
                # template (base.html's navbar bell) without every single
                # view having to remember to pass it in manually.
                'notifications.context_processors.unread_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Caching — see Module 12. LocMemCache lives inside this one process, which
# is fine for local dev and for this course, but NOT for a real multi-process
# deployment (each worker process would have its own separate cache, so one
# worker invalidating a key wouldn't affect the others). Module 16 swaps
# this for Redis, shared across every process, without changing any code
# that calls cache.get()/set() — that's the point of the cache abstraction.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Project-wide static assets (shared CSS/JS/images) live in BASE_DIR/static.
# App-specific static files still auto-discover from each app's static/ folder.
STATICFILES_DIRS = [BASE_DIR / 'static']

# User-uploaded files (product images) — distinct from STATIC_*, which is
# for files that ship WITH the code. MEDIA_ROOT is gitignored (see
# .gitignore); config/urls.py serves MEDIA_URL only while DEBUG=True.
# Module 16 replaces local disk storage with real object storage (S3 or
# equivalent) for production, where the filesystem isn't persistent/shared
# across deployments.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/models/fields/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Our own User model, swapped in via Module 08 — see accounts/models.py.
# This MUST be set before the first migrate() that touches the user model;
# see the Module 08 lesson for what goes wrong if you change it afterwards.
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'pages:home'
LOGOUT_REDIRECT_URL = 'pages:home'

# Django's messages framework tags a message "error"; Bootstrap's alert
# class is "danger" — remap so {{ message.tags }} lines up with Bootstrap's
# alert-{{ message.tags }} classes in base.html without a template-side hack.
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.ERROR: "danger",
}

# Django REST Framework — see Module 10.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # SessionAuthentication: lets you browse the API while logged into
        # the site (powers the browsable API UI at /api/).
        "rest_framework.authentication.SessionAuthentication",
        # TokenAuthentication: what a real API client (mobile app, another
        # service, a script) uses instead — a header, not a browser cookie.
        "rest_framework.authentication.TokenAuthentication",
    ],
    # Mirrors the web UI's default: read is public, write requires the
    # same Django model permissions the admin/web views already enforce
    # (e.g. catalog.add_product) — one permission system, two frontends.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # Throttling — Module 15. Without this, nothing stops a script from
    # hammering /api/token/ trying passwords, or scraping the whole
    # catalog in a tight loop. Two separate rates because an anonymous
    # caller and an authenticated one are different risk levels — a
    # logged-in user has already proven who they are, so they get a much
    # higher ceiling than an anonymous one.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/minute",
        "user": "100/minute",
    },
}

# Email — console backend prints "sent" emails to the terminal instead of
# actually sending, perfect for local development. Module 16 covers a real
# SMTP/transactional-email-provider backend for production.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'orders@atlas.example'

# Celery — see Module 13. Real deployments need Redis (or another real
# broker) running; CELERY_TASK_ALWAYS_EAGER lets tests run task code
# synchronously, in-process, with no broker at all.
#
# This deliberately checks `'pytest' in sys.modules` rather than an
# env var conftest.py sets before importing Django. That was the first
# approach tried here, and it silently didn't work: pytest-django calls
# django.setup() (which builds config/celery.py's Celery app and caches
# its config) from ITS OWN pytest_configure hook, which runs before the
# project's root conftest.py module body ever executes — so by the time
# conftest.py set the env var, Celery had already cached
# task_always_eager=False and a real Redis result backend, permanently,
# for the rest of the process. Every `.delay()` call in the suite then
# tried to actually talk to Redis. `'pytest' in sys.modules` sidesteps
# the ordering problem entirely: pytest necessarily imports itself
# before it can call any hook, so this is already True the first time
# settings.py runs under pytest, no matter how early that is.
CELERY_TASK_ALWAYS_EAGER = 'pytest' in sys.modules
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')

if CELERY_TASK_ALWAYS_EAGER:
    # Even in eager mode, Celery still tries to store each task's result
    # in whatever CELERY_RESULT_BACKEND is configured — pointing that at
    # Redis here would make every test try (and fail, repeatedly retrying)
    # to connect to a broker that isn't running. None of our code calls
    # .get() on a task's result, so there's nothing to actually store.
    CELERY_RESULT_BACKEND = None
    CELERY_TASK_STORE_EAGER_RESULT = False
else:
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'daily-low-stock-report': {
        'task': 'catalog.tasks.send_low_stock_report',
        'schedule': crontab(hour=8, minute=0),
    },
}
